// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
	call_to_action: dynamic(() => import("./CallToAction")),
	contact_form: dynamic(() => import("./ContactForm")),
	cover: dynamic(() => import("./Cover")),
	features: dynamic(() => import("./Features")),
	hero: dynamic(() => import("./Hero")),
	image: dynamic(() => import("./Image")),
	image_grid: dynamic(() => import("./ImageGrid")),
	pricing_table: dynamic(() => import("./PricingTable")),
};
